### ISSUE TITLE
Reco1 multi-TPC SCE configuration appears broken

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/icaruscode#136]
Reported by @gMoreno05 while running `reco_icarus_driver_reco_multitpc_gauss_sce.fcl`:
```
%MSG-s ArtException:  PostEndJob 18-Mar-2021 14:34:38 CDT ModuleEndJob
---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- ScheduleExecutionFailure BEGIN
    Path: ProcessingStopped.
    ---- ProductNotFound BEGIN
      Found zero products matching all selection criteria
        C++ type: std::vector<recob::PFParticle>
        Module label: 'pandoraGaus'
        Product instance name: ''
        Process name: (empty)The above exception was thrown while processing module TrackProducerFromPFParticle/pandoraKalmanTrackICARUSCryo0 run: 1 subRun: 0 event: 1
    ---- ProductNotFound END
    Exception going through path reco
  ---- ScheduleExecutionFailure END
---- EventProcessorFailure END
```

New in `v09_18_00`.
Some input labels apparently need to be fixed.

**Comment by PetrilloAtWork** [comment]
Needless to say, C.I. would help here.
Just saying.

**Comment by SFBayLaser** [comment]
Ok, this issue is understood and will attempt to get a fix into the next release. 
In the meantime, if working with sim/recon, perhaps this could be avoided by using an older release?

**Comment by SFBayLaser** [comment]
A temporary patch has been applied which simply removes the kalman filter track fit from the "icarus" path for now. Not the correct or even ideal solution but was in need of an interim release and this should prevent jobs from crashing if using that release. So, keep this open until right solution implemented.

**Comment by wesketchum** [comment]
@SFBayLaser @PetrilloAtWork is this past a temp fix and can be closed? Or needs more work?

**Comment by SFBayLaser** [comment]
I think we are done with this and it can be closed. The tracking folks are moving along and will address the "right" solution when they need it.

**Comment by brucehoward-physics** [comment]
Is there even an SCE correction path being used in the "ICARUS" hit chain, let alone for Kalman tracks specifically?

**Comment by wesketchum** [comment]
Closing based on @SFBayLaser 's coment. (@brucehoward-physics don't know the answer to your q...)
