### ISSUE TITLE
Update the enable time of PMT simulation

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/icaruscode#14]
The current setting is for 2.8 ms, while the planned one is 2.0 ms.
Need to be careful to set the offsets correctly (it should be starting 1 ms before the beam gate opening time).

**Comment by SFBayLaser** [comment]
Is there an update to this issue?

**Comment by PetrilloAtWork** [comment]
Not really. In fact, I had forgotten about it.
Let's pull in somebody in DAQ, like @wesketchum , to ask if the information that the readout of PMT is enabled from -1 ms to +1 ms with respect to the expected beam gate opening (I can't find Angela Fava user here, or I would bother her too).
My understanding was that at -1 ms the readout board caches are flushed, and 2 ms after that what is in the cache is transferred (if a trigger has happened).

**Comment by wesketchum** [comment]
Good q. I'm not sure what the PMT guys have decided on the timing. It's configurable, so I think it could be more ... I'll try to followup.

**Comment by SFBayLaser** [comment]
Is there an update to this issue?

**Comment by wesketchum** [comment]
Pinging again, and maybe pinging myself. What is needed to close this out?

**Comment by PetrilloAtWork** [comment]
Mostly some clarity about what the readout/DAQ configuration is going to be.
I think we are going to get there with the first commissioning of the multi-window PMT acquisition (i.e. storing interesting PMT waveforms even out of the beam gate), which should happen in one-two months time scale.
