### ISSUE TITLE
GEANT4 simulation for neutrino + cosmic ray samples

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/icaruscode#143]
It turns out that in some old production we have used the "standard" `LArG4` configuration to process the neutrino + cosmic ray samples.
As a reminder, we have a `standard_g4_icarus.fcl` configuration which saves everything and everywhere, and a set `cosmics_g4_icarus[_volCryostat,_volDetEnc].fcl` which has a higher energy requirement and may have a volume constraint (these requirements affect whether the particle truth information is saved, but the particles are always simulated and always deposit energy).

I argue that our production of cosmic rays should always use `cosmics_g4_icarus_volDetEnc.fcl` or tighter, except for special needs where the whole cosmic ray shower history is needed.

Interest party: production (@mayawos, Francois Drielsma), software coordination (@SFBayLaser, Daniele Gibin).

**Comment by wesketchum** [comment]
Looping in @hgreenlee and ... well, wanted to loop in Sophie but invitation to SBNSoftware is pending.

@SFBayLaser , @PetrilloAtWork , please comment if any change on this or if it's still true.

**Comment by PetrilloAtWork** [comment]
Pushing the ball into François and @SFBayLaser court (I never remember François's GitHub user...).

**Comment by SFBayLaser** [comment]
@francois-drielsma

**Comment by SFBayLaser** [comment]
note that with [PR 214](https://github.com/SBNSoftware/icaruscode/pull/214) we have stopped storing shower daughters by default (meaning you have to turn that back on to get the full tree). If I understand correctly, Gianluca's solution above sets a higher kinetic energy cut AND restricts particles to be in the cryostat. I would leave it to @PetrilloAtWork to comment on whether simply eliminating the shower daughters would be sufficient or we still need to use the recommended fcl files above.

**Comment by jzennamo** [comment]
Is this also an issue for in-time generation fcls?

**Comment by wesketchum** [comment]
I'm moving this to the 2021B_XX project...though we should close it if it is a closed issue. If we need new fhicls/updates to workflows we should make those as part of a patch.

**Comment by wesketchum** [comment]
Now defined as per v09_28_01_01 release.
