### ISSUE TITLE
Channel mapping database: C:1 T:3 P:2 

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/icaruscode#145]
`C:1 T:3 P:2 W:1176-1400` appear to have cable mapping inverted.
This was observed in event `R:5291 E:18972` (`data_dl19_run5291_15_20210320T003109.root`).
The file was processed on `2021-03-20T05:56:51+00:00` according to SAM metadata.

Note that the range reported above is approximate and a thorough check should be performed to discover the proper cables (likely, 9 of them).

Reported by @dkoh0207 (Dae Heun Koh).
Channel mapping crew! @SFBayLaser, @biswaranjan91, @varanini!

**Comment by biswaranjan91** [comment]
This has been fixed with the v09_26_00 release.
