### ISSUE TITLE
PMT readout fragment ID change

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/icaruscode#151]
Recently the ID of the fragments from PMT readout boards (V1730) has changed (from `N` to `0x2000 + N`).
User code needs to mask the additional bits to access the PMT channel mapping database, which retains the old fragment ID values.

The standard interface to access that PMT channel mapping database from LArSoft environment is the service family `IICARUSChannelMap`, some methods of which accept a fragment ID as argument.
I suggest that this service automatically transform the PMT fragment ID, lifting the users from being aware of that implementation detail.

**Comment by PetrilloAtWork** [comment]
This is a request for comments on the idea. Among the people involved: @wesketchum, @SFBayLaser, @ascarpel.

**Comment by wesketchum** [comment]
This is resolved? If so, @PetrilloAtWork, @SFBayLaser , @ascarpel  or someone who can confirm, please close?

**Comment by PetrilloAtWork** [comment]
I don't think it has been addressed.
I still see no masking in `ICARUSChannelMapProvider.cxx`.
@ascarpel, @animeshgit20, @biswaranjan91 , what is the fragment ID key in the PMT channel mapping database now? pattern `0x20xx` or `0x00xx`?

**Comment by wesketchum** [comment]
@PetrilloAtWork @ascarpel @animeshgit20 @biswaranjan91 I think at this point this has been fixed? If so, let's close this out?

**Comment by biswaranjan91** [comment]
FragmentID for PMT in the database is an integer from 0 to 23. 
Still it has not in the  pattern of 0x20xx or 0x00xx.
From my recollection, PMT decoder level it has changed, however we have not changed in the database level. May be Andrea(@ascarpel) can help on confirming this. I can check but not sure which fhicl file was used officially for PMT decoder.

**Comment by PetrilloAtWork** [comment]
The issue was to elicit comments on encoding the database key (0-23) in the interface to the database.
Neither this has been implemented, nor opinions have been offered. So no, not done yet.

**Comment by PetrilloAtWork** [comment]
I have opened a pull request with a proposed implementation.
Let's see if this can push the issue toward its conclusion.

**Comment by wesketchum** [comment]
PR has been merged, so claiming this is done.
