### ISSUE TITLE
Pedestal Computation in PMT Reconstruction is Printing a lot of Error Messages

### ISSUE THREAD

**Issue by gputnam** [SBNSoftware/icaruscode#201]
When running the existing ICARUS PMT reconstruction, there are a lot of error messages: 

> ^[[93m<<CheckSanity>>^[[00m Could not find good pedestal at all...

See, for example: `/pnfs/icarus/scratch/users/gputnam/icarus-sce-testing/muonB_cryo1/46600503_150/46600503_150.log`.

I have tracked down the source of this error message to: https://github.com/LArSoft/larana/blob/53e16719e2167dcab8852500b5ddb93cb3874ca2/larana/OpticalDetector/OpHitFinder/PedAlgoRmsSlider.cxx#L411.

**Comment by wesketchum** [comment]
@SFBayLaser , can you help assign someone to followup on this? (Or otherwise comment?)

**Comment by wesketchum** [comment]
@SFBayLaser @PetrilloAtWork @ascarpel comment on this? If it's a real error we should make sure to address. If it's not we should remove the warning message...

**Comment by wesketchum** [comment]
OK, I'm running over recent files now in near-ICARUS prod release and not seeing these warnings so much, so I'm going to close this issue. Can reopen as needed.
