### ISSUE TITLE
ICARUS Noise Simulation Updates

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/icaruscode#218]
Issue to capture work on noise model updates for ICARUS simulation (@varanini is working on it I believe...). Filippo, please comment/expand/modify/etc. as you see fit.

Adding to to project tracking for 13 Aug production: if it's ready by then, great, otherwise will be pushed to Oct 1.

**Comment by SFBayLaser** [comment]
I have not seen an update from Filippo and assume this will not get included in this week's release (due out Sunday, Aug 1).

**Comment by wesketchum** [comment]
Believe #228 resolves this issue. @varanini or @SFBayLaser is it in standard fcls?

**Comment by jzennamo** [comment]
@SFBayLaser confirms that this is now working and configured by default. Thanks Tracy!
