### ISSUE TITLE
Update to 2D ROI finding in ICARUS

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/icaruscode#220]
Placeholder issue for ROI finding updates in ICARUS (believe work from Dae ... assigning @SFBayLaser to track/provide more clarity as to what needs to be done).

**Comment by SFBayLaser** [comment]
There are two versions and we use the first in production now - an "ROI finder" runs post deconvolution and uses the old school 2D morphological functions to find the ROIs. Works ok. The better version which finds ROIs during noise filtering is now working properly and will be part of next release. But will need study/tuning to optimize.

**Comment by SFBayLaser** [comment]
https://github.com/SBNSoftware/icaruscode/pull/221 will include the code to run the "new" ROI finding on the raw images and then output those (right now in the form of Wire objects) which are then picked up after deconvolution to determine the ROIs to applied to those waveforms. Will include this in the next release (Sunday morning is target).

**Comment by wesketchum** [comment]
Thanks @SFBayLaser. Going to close this issue. Can open another one for tuning/optimization as needed.
