### ISSUE TITLE
Include Simple-Flash Matcher to the standard chain of reconstruction

### ISSUE THREAD

**Issue by ikatza** [SBNSoftware/icaruscode#225]
The Simple-Flash Matcher was designed for `sbndcode` and `icaruscode`. Is routinely used by analysers on both collaborations and is already part of the standard record of CAFAna. Importantly it is a key element of the numu and nue selection studies in ICARUS and also used for NuMI selection.

As a guide this commit shows the changes made for `sbndcode`:
https://github.com/SBNSoftware/sbndcode/commit/156f106b91a8664c7ab18292f1059ca2f7cb8d25

Note that not all of them might be relevant for `icaruscode`.

I believe this is crucial to have included for the upcoming production.

**Comment by brucehoward-physics** [comment]
I think this is the issue that Iker just mentioned to @jzettle in a shared chat we were just having? If so this _might_ be something that Jacob would look into as he is thinking to take a look at some of the data.

**Comment by jzettle** [comment]
I can attempt to look at this if I can navigate the fcl maze to find the right places for this in the standard files

**Comment by wesketchum** [comment]
Wonderful, just officially assigned @jzettle to it then.

**Comment by wesketchum** [comment]
@jzettle any progress on this?

**Comment by jzettle** [comment]
@wesketchum Not quite yet. Trying to navigate where this should go without much understanding of how this standard reconstruction chain works or is run is difficult.

**Comment by jzettle** [comment]
So I tried to include this in what I think is a relevant place, but I have absolutely no experience in using this so it's difficult to understand if I've done something that makes sense. Now I will try to somehow run something to test this and try to make changes if needed. If there's a standard pathway for testing these changes that would be much appreciated to know what that is.

**Comment by brucehoward-physics** [comment]
So, I was thinking about this, and I think probably this change/updating belongs as part of the changes in this PR grouping no?

https://github.com/SBNSoftware/icaruscode/pull/223

Tagging @gputnam in case he thinks differently.

**Comment by SFBayLaser** [comment]
Sorry, wasting all of my time in fallout from release yesterday. We REALLY need someone else doing that job!
Anyway, the aim for the next production is to follow a reconstruction path for simulation that is nearer to the data path we are running now so there are new fhicl files to be run in this case. The equivalent to "stage 1" is where we will be adding more higher level reconstruction items. For this thread note that the optical hits and flashes are done in stage 0 (so we can use an optical filter if we want) so it is only the higher level matching that needs to be done in stage 1.

**Comment by SFBayLaser** [comment]
The draft version for stage 1 is located at https://github.com/SBNSoftware/icaruscode/blob/develop/icaruscode/Decode/fcl/stage1_multiTPC_icarus_gauss_MC.fcl
I think @gputnam has some updates for this already but not sure if on feature branch yet?

**Comment by jzettle** [comment]
@SFBayLaser So the suggestion is to place this in the same "defs" file (stage1_icarus_defs.fcl) as some of these other things (as this has been used in both data and MC) and then add that within the file you linked? I feel I'm more confused on where this is meant to go. I apologize, I don't have much understanding of how all this works so it feels as though I'm missing some fundamental piece here. There are many fcl files in many different places so it's a bit difficult to understand what is relevant in following the includes backwards.

**Comment by jzettle** [comment]
@wesketchum So I have attempted to complete this in a feature branch here: https://github.com/SBNSoftware/icaruscode/tree/feature_jzettleFMatchICARUSStandardReco. I am somewhat unsure if I have the right idea here and I am not sure how to successfully test that this doesn't break anything as trying to follow MC generation from the production spreadsheet was unsuccessful in even getting to this stage. If this is not the correct idea, I would relish the opportunity to have a discussion with somebody on how all of this works and goes together so I have a better view. Thanks.

**Comment by brucehoward-physics** [comment]
From a *very* quick look that seems like the right idea - were you able to get it to run in data and produce FM results? Which sim did you try to use?

**Comment by brucehoward-physics** [comment]
Also I guess I should say that @SFBayLaser started a feature branch (https://github.com/SBNSoftware/icaruscode/tree/feature/usher_data_MC_fhicl_updates), so I guess instead of the relevant PR being https://github.com/SBNSoftware/icaruscode/pull/223 that I mentioned above, maybe this branch is the more appropriate place to be looking 😅

**Comment by wesketchum** [comment]
Closing as it has been merged in with #223
