### ISSUE TITLE
Change ICARUS CORSIKA configurations to use proton-model 

### ISSUE THREAD

**Issue by jzennamo** [SBNSoftware/icaruscode#229]
My understanding was that for the August production we wanted to use the proton-model for CORSIKA cosmic simulation, but when I reviewed `prodcorsika_genie_overburden_icarus.fcl` it looks to be calling other CORSIKA database files. Can people confirm that this fcl is what we want to use for the production samples?

**Comment by PetrilloAtWork** [comment]
I confirm _it is not_. The proton configuration is without overburden, and the overburden configuration is CMC.

**Comment by PetrilloAtWork** [comment]
I have pushed a `prodcorsika_genie_protononly_overburden_icarus.fcl` in pull request #223 (branch `feature/MCP2021Reco`) that should do the standard stuff in the standard way.
Something is broken in my box though, so I could not test it.

**Comment by cfarnese** [comment]
Thanks Gianluca for this commit! One thing I am not able to understand simply looking to the code is: in which volume are we simulating? In the past we used VolCryostat but now the request is to simulate on both cryostat so we need to check for it (using for example volDetEnclosure)... can you confirm that we are now using this volume?

**Comment by cfarnese** [comment]
Update: I made a small test and I can confirm that the used volume allows to have neutrinos in both cryostats! As in the past, after this gen stage we need  to run the filter_genie_active_icarus.fcl and it seems that only ~40% of the events survive the filter... I hope it helps!

**Comment by jzennamo** [comment]
Great, thanks both!
