### ISSUE TITLE
No overburden G4 configuration fcl

### ISSUE THREAD

**Issue by jzennamo** [SBNSoftware/icaruscode#240]
For the start of production, we wanted to create some samples for ICARUS without overburden but I am having trouble finding a G4 fcl that enables this workflow. I thought that maybe `g4_enable_spacecharge.fcl` would do it but it looks like there are other differences from the standard `g4_enable_spacecharge_cosmics_ovb.fcl`. Is this the correct fcl to be using? Are the other changes not "impactful"?

```
diff g4_enable_spacecharge.dump ../g4/g4_enable_spacecharge_cosmics_ovb.dump 
2c2
< #   Input  : g4_enable_spacecharge.fcl
---
> #   Input  : g4_enable_spacecharge_cosmics_ovb.fcl
32c32,34
<          KeepParticlesInVolumes: []
---
>          KeepParticlesInVolumes: [
>             "volDetEnclosure"
>          ]
136c138
<       GDML: "icarus_complete_20210527_no_overburden.gdml"
---
>       GDML: "icarus_complete_20210527_overburden.gdml"
138c140
<       ROOT: "icarus_complete_20210527_no_overburden.gdml"
---
>       ROOT: "icarus_complete_20210527_overburden.gdml"
202c204
<       ParticleKineticEnergyCut: 1e-5
---
>       ParticleKineticEnergyCut: 5e-4
```

**Comment by PetrilloAtWork** [comment]
The configuration `cosmics_g4_icarus_sce_nooverburden.fcl` was added with pull request #241 for production.
`g4_enable_spacecharge.fcl` does not have our common settings for cosmic rays (for what is worth).
