### ISSUE TITLE
Restore (modified) per-event random policy as default

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/icaruscode#243]
LArSoft `v09_28_02` adopts a newer version of `nugen` which introduces some level of control for seeds outside `art::Event` in the `perEvent` random seed policy.

As a reminder, the original issue, reported as [LArSoft issue #26116](https://cdcvs.fnal.gov/redmine/issues/26116), was that `perEvent` policy would set the random seeds only just before processing each event, so that the engine seeds remain uninitialised (or better, initialised to `0`) from the beginning of the job until the first event.
This caused major issues in `CORSIKAGen`, whose `beginJob()` would use a random generator to pick one of the available database files, and possibly to `GENIEGen` and others.

The new `perEvent` policy allows to specify a fallback policy (`initSeedPolicy`) being used when not in processing an event. This is not a perfect solution, but provides some control before the first event.
Given the known behaviour of `CORSIKAGen`, I advocate the restoration of `perEvent` as main policy, using `random` as fallback. This makes it much harder to exactly reproduce _some_ jobs (still possible via a master seed though), but it "guarantees" no fixed seed.

This issue should be addressed when LArSoft `v09_28_02` or newer is adopted in `icaruscode`.

**Comment by wesketchum** [comment]
@PetrilloAtWork has this been done, now that we're beyond this LArSoft version?
