### ISSUE TITLE
Update noise reduction factor in ICARUS noise simulation

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/icaruscode#246]
Re: conversation at SBN AI meeting 24 Aug, need to update the noise model reduction factor from 0.6 to 0.8 (or expert recommendation) ASAP for SBN2021B production.

**Comment by SFBayLaser** [comment]
By agreement after the Analysis Infrastructure meeting we agreed to set the scaling factor to 0.8 for now.
