### ISSUE TITLE
Include weight production to the ICARUS CAFMaker fcl

### ISSUE THREAD

**Issue by FernandaPsihas** [SBNSoftware/icaruscode#250]
An equivalent fcl to https://github.com/SBNSoftware/sbncode/blob/develop/fcl/caf/sbnd/cafmakerjob_sbnd_sce_geniewgt.fcl is needed to produce CAFs with genie weights.

**Comment by wesketchum** [comment]
@FernandaPsihas @PetrilloAtWork any update on this? Can you coordinate this work if it's not in?
