### ISSUE TITLE
Update in coherent noise model

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/icaruscode#280]
Need an update to correlate coherent noise across planes. @varanini working on this, and will pass along to @rennney and others for further validation. (Further details welcome!)

**Comment by wesketchum** [comment]
Don't know if this is related to #284 or not. Would be good to followup on that/close the loop.

**Comment by jzennamo** [comment]
@SFBayLaser I think your recent pushes addressed this correct? Can we close this?

**Comment by jzennamo** [comment]
Specifically https://github.com/SBNSoftware/icaruscode/pull/284 and https://github.com/SBNSoftware/icaruscode/pull/294

**Comment by SFBayLaser** [comment]
Not quite yet. What has been done up to now is to include the ability to simulate noise in the TPC on a readout board basis (64 channels). The initial FFT histograms to generate this noise, based on small statistics, has been included in icarus_data. 
To do:

1. Update the FFT histograms with a more complete sampling of the noise from data. This is work in progress with the first bit to simply get more statistics but also to understand how to sample the noise but not include signal. 
2. This all needs to be imported into the 2D drift simulation. The contact person for this work is out for a week or so. 

Probably we need to keep this open until both are addressed.

**Comment by jzennamo** [comment]
Thanks for the update!

**Comment by SFBayLaser** [comment]
Wow! This got left hanging for a long time when it should have been closed out. Generally, the noise model for both the 1D and 2D drift simulations has been updated and matched to data as well as possible at this point. This is being done on a per board basis so is quite granular. So I am going to go ahead and close this out.
