### ISSUE TITLE
Relative position of NuMI beam to detector needs update

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/icaruscode#3]
The relative position of NuMI beam to detector needs update.

**Comment by PetrilloAtWork** [comment]
Involved people: @aaduszki

**Comment by SFBayLaser** [comment]
Should this be a pull request?

**Comment by SFBayLaser** [comment]
Is there an update to this issue?

**Comment by aaduszki** [comment]
We are waiting for response from Claudio. By the way, the issue affects not only position w.r.t. NuMI beam, but also BNB beam.

**Comment by SFBayLaser** [comment]
Is there an update to this issue?

**Comment by wesketchum** [comment]
Pinging again on this: would be great to get an update @aaduszki.

**Comment by SFBayLaser** [comment]
I believe there is one more planned movement getting introduced shortly...

**Comment by wesketchum** [comment]
I see a PR here. Is this resolved @SFBayLaser ?

**Comment by PetrilloAtWork** [comment]
Which pull request?
Laura's commit seems unrelated (but a keyword in the commit message has inspired GitHub a connection).
