### ISSUE TITLE
Unreadable data files with icaruscode v09_51_00

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/icaruscode#401]
The last commit here https://github.com/SBNSoftware/icaruscode/pull/375/commits/41ddf9b5729210bd179086d27da655797c27afb0 causes trouble looking like

`       The StreamerInfo of class sbn::ExtraTriggerInfo read from file XXX`
`       has the same version (=10) as the active class but a different checksum.`
`       You should update the version to ClassDef(sbn::ExtraTriggerInfo,11).`
`       Do not try to write objects with the current class definition,`
`       the files will not be readable.`

@PetrilloAtWork was asking just to remove the new intermediate versions that were added as part of this work. But you have also removed the pre-existing version 10 of ExtraTriggerInfo, and updated the checksums to the new one appropriate for version 11. This makes it impossible to open old files, and probably causes chaos if saving files from this version.

Unfortunately, this change has already made it into the icaruscode v09_51_00 release...

_Originally posted by @cjbackhouse in https://github.com/SBNSoftware/icaruscode/issues/375#issuecomment-1132256471_

**Comment by PetrilloAtWork** [comment]
I think that the solution is to restore the old checksum and pretend nothing happened.
The only permanent impact is with people creating files with `v09_51_00`, which is only for data files, only for runs before April, and only for full (`Stage0`) decoding.

**Comment by cjbackhouse** [comment]
I'm surprised that the release build allowed a checksum to be specified that differs from the original (presumably still correct) v10 checksum. If we can confirm that removing the checksum completely and rebuilding gives the old v10 checksum then I agree with @PetrilloAtWork

**Comment by PetrilloAtWork** [comment]
... and by mistake commit bb19d51 doing that landed into `develop`.

**Comment by rennney** [comment]
Hello, I want to make sure I understand that you decided to do. I assume the last commit from @PetrilloAtWork to develop fixes the issue and we will release v09_52_00 with this fix, while the version v09_51_00 will be left behind. 

PS. I wonder why the CI build was successful, it looks like the issue that should have broken the initial build. 


Adding @mmrosenberg

**Comment by PetrilloAtWork** [comment]
The commit _could_ fix it... it was not tested. I am doing it now.

**Comment by PetrilloAtWork** [comment]
The commit does _not_ solve the issue. I'll revert it.

**Comment by PetrilloAtWork** [comment]
> PS. I wonder why the CI build was successful, it looks like the issue that should have broken the initial build.

I am not sure about the build itself; for the C.I. _tests_, this data product is produced only on data, and I believe there is no data yet in the tests.

**Comment by PetrilloAtWork** [comment]
I have requested a pull of the fix (#402). I am still not sure about what happened, but I think it stemmed from a wrong request I made during the code review.

**Comment by rennney** [comment]
Ok, it will go in v09_52_00 most likely tomorrow. Thank you for fast fix!
