### ISSUE TITLE
Retain partial optical detector waveforms in the reconstruction files

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/icaruscode#451]
As part of the plan to reduce the storage requirements of ICARUS data, optical detector waveforms are being dropped from `Stage1` (and possibly `Stage0`) output.
Given that this loss is effectively irreversible due to the costs involved in processing the data again, there is desire to retain at least part of that information for future improvements.
The gamble is to write information that may be useful in the future, without knowing exactly which developments may utilise it.

Several proposals have been made, including:
1. retain an interval for each reconstructed hit
2. retain an interval for each reconstructed flash
3. retain the full waveform information only around the beam gate
4. discretise the waveforms into a new data product

Whatever is decided, it needs to be deployed before ICARUS Run2 data processing starts.

**Comment by SFBayLaser** [comment]
Is this possibly another use case for ChannelROI?

**Comment by wesketchum** [comment]
Fixed by #478 (I think ... in part at least ...)

**Comment by PetrilloAtWork** [comment]
PR #478 implements option 3 (retain the full waveform information only around the beam gate), but it does not change the standard workflow to use the new feature.

**Comment by PetrilloAtWork** [comment]
Resolved by #504.
