### ISSUE TITLE
Update production fhicl files for Stage 0

### ISSUE THREAD

**Issue by SFBayLaser** [SBNSoftware/icaruscode#453]
The standard "run 1" fhicl files will need updating for production running when we start run 2, nominally beginning mid-October.

**Comment by SFBayLaser** [comment]
Starting a list of changes in stage 0 fhicl files:

1. drop all output from decoding stage
2. drop recob::Wire output from deconvolution and ROI finding stages
3. keep recob::ChannelROI output from the ROI finding stage
4. keep some form of PMT waveform output (TBD)

**Comment by SFBayLaser** [comment]
Necessary "Run 2" fhicl files:

1. 'stage0_run2_icarus..fcl' which should be the default fcl file for production
2. 'stage0_run2_raw_icarus.fcl' which is the default fhicl file but maintains noise filter RawDigits for scanning purposes
3. 'stage0_run2_wc_icarus.fcl' which uses the 2D deconvolution
4. 'stage0_run2_icarus_mc.fcl' which is the default fhicl file for MC 
5. 'stage0_run2_raw_icarus_mc.fcl' which is the above but keeps noise filtered RawDigits for scanning purposes
6. 'stage0_run2_icarus_mc_lite.fcl' which is the "lite" version of the MC output (reduced truth information)
7. 'stage0_run2_wc_icarus.fcl' which uses the 2D deconvolution

**Comment by SFBayLaser** [comment]
Should we do some general cleanup of the decoder fcl directory? Essentially, move all fcl files associated to previous runs to a subfolder...

**Comment by PetrilloAtWork** [comment]
Non-production configurations to be preserved: PMT and trigger take:
* `decodePMT_icarus.fcl`
* `decodeTrigger_icarus.fcl`
* `dump_artfragments_pmt_icarus.fcl`
* `dump_triggers_icarus.fcl`

Known dependencies:
* `CAEN_V1730_setup_icarus.fcl`
* `decodePMTdefs_icarus.fcl`

**Comment by SFBayLaser** [comment]
The first PR is now available: https://github.com/SBNSoftware/icaruscode/pull/458

**Comment by wesketchum** [comment]
OK, @SFBayLaser a part2 still ongoing here? Just want to make sure we don't close if not finished.

**Comment by cerati** [comment]
looks like #482 is the last PR for this issue, right?

**Comment by wesketchum** [comment]
Calling this done. If we need to do more, we can reopen or make a new issue/PR.
