### ISSUE TITLE
Define the correct detector simulation fhicl file

### ISSUE THREAD

**Issue by SFBayLaser** [SBNSoftware/icaruscode#761]
Between icaruscode [v09_84_00_03](https://github.com/SBNSoftware/icaruscode/blob/v09_84_00_03/fcl/detsim/detsim_2d_icarus_refactored.fcl) and icaruscode [v09_89_01_01p02](https://github.com/SBNSoftware/icaruscode/tree/v09_89_01_01p02) there are differences in detector simlation fhicl files. 

In particular, v09_89_01_01p02 the detector simulation has two variations of fhicl files: `detsim_2d_icarus_refactored.fcl` and `detsim_2d_icarus_fitFR_refactored.fcl` (where "refactored" refers to utilizing input files from the refactored G4). 

In addition there are differences in parameters, for example electronics gains and the shaping time on plane 1.

**Comment by SFBayLaser** [comment]
In v09_89_01_01 the difference between using the default refactored fhicl file and one that had "fitFR" is the following:
/icarus_simwire_wirecell_fitSR: @local::icarus_simwire_wirecell
# Add in the ER tail
icarus_simwire_wirecell_fitSR.wcls_main.params.file_rcresp: "icarus_fnal_rc_tail.json"
# Add in the tuned field responses
icarus_simwire_wirecell_fitSR.wcls_main.params.files_fields: "icarus_fnal_fit_ks_P0nom.json.bz2"
# futz with shaping+gain values (note these are really just scale factors and should not be taken literally)
icarus_simwire_wirecell_fitSR.wcls_main.structs.gain0: 11.9918701 # mV/fC 
icarus_simwire_wirecell_fitSR.wcls_main.structs.gain1: 12.6181926 # mV/fC
icarus_simwire_wirecell_fitSR.wcls_main.structs.gain2: 13.0261362 # mV/fC
icarus_simwire_wirecell_fitSR.wcls_main.structs.shaping1: 1.45 # us

/

**Comment by jzettle** [comment]
@SFBayLaser @etworcester I created a branch that commits the changes needed to the detector variation sample fhicl files here: https://github.com/SBNSoftware/icaruscode/tree/feature/jzettle_updatedetsim_variations/fcl/syst_variations. I can create a pull request when we have the tag (or I can just make it against the existing release now if that is easier). I also cleaned up the fhicl directory there to only include the fhicls we intend to use (or are a backup plan) for the variation samples so they are easier to follow and review

Please make sure that someone can seriously review the request to make sure have done what we intended here.

**Comment by jzettle** [comment]
This got merged as PR #771 in the v09_89_01_01p03 release. In case there is bookkeeping for this that we want

**Comment by jzettle** [comment]
Should we move this to completed or was this still open? The fix got merged and implemented in the current productions

**Comment by SFBayLaser** [comment]
Yes, you are correct. Closing.
